{% set name = "django-pwa" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-pwa-{{ version }}.tar.gz
  sha256: 07ed9dd57108838e3fe44b551a82032ca4ed76e31cb3c3e8d51604e0fe7e81e9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python {{ python_min }}
  run:
    - django >=1.8
    - python >={{ python_min }}

test:
  imports:
    - pwa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/silviolleite/django-pwa
  summary: A Django app to include a manifest.json and Service Worker instance to enable progressive web app behavior
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kcemenike
